name: Mobile Tests

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  mobile:
    runs-on: ubuntu-latest

    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Appium
        run: |
          npm install -g appium
          appium driver install uiautomator2

      - name: Run Android Emulator and Tests
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 34
          arch: x86_64
          profile: pixel_6
          disable-animations: true
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim

          script: |
            appium --log-level info > appium.log 2>&1 &

            echo "Waiting Appium..."
            sleep 15

            mvn clean test -Dtest=MobileTestRunner

      - name: Upload Appium Log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: appium-log
          path: appium.log

      - name: Upload Surefire Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports